example/foo/urls.py
from django.conf.urls.defaults import *

from forms import Example3

urlpatterns = patterns('',
    url(r'^1/$', 'foo.views.example1', name='example1'),
    url(r'^2/$', 'foo.views.example2', name='example2'),
    url(r'^3/$', 'foo.views.example3', name='example3'),
    url(r'^4/$', 'foo.views.example4', name='example4'),

    url(r'^ajax/3/(?P<field_name>[\w_]+)/$', 'ajax_forms.views.validate', {'form_class': Example3}, name='ajax_example3'),
)

example/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    (r'^foo/', include('example.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    # Catch all
    url(r'test/', 'django.views.generic.simple.direct_to_template', {"template": "foo/test.html"}),
    url(r'^.*', 'django.views.generic.simple.direct_to_template', {"template": "foo/home.html"}),
)

example/foo/models.py
from django.db import models

# Create your models here.

example/foo/forms.py
from decimal import Decimal
from django import forms

class Example1(forms.Form):
    CHOICES = (
        (1, 'First'),
        (2, 'Second'),
        (3, 'Third'),
        (4, 'Fourth'),
    )

    boolean = forms.BooleanField(label='BooleanField')
    charfield = forms.CharField(label='CharField', max_length=30, min_length=3)
    choicefield = forms.ChoiceField(label='ChoiceField', choices=CHOICES)
    typedchoicefield = forms.TypedChoiceField(label='TypedChoiceField', choices=CHOICES, empty_value=0, coerce=int)
    datefield = forms.DateField(label='DateField')
    datetimefield = forms.DateTimeField(label='DateTimeField')
    decimalfield = forms.DecimalField(label='DecimalField', max_value=Decimal('2291.3321'), min_value=Decimal('432.3244'), max_digits=9, decimal_places=4)
    emailfield = forms.EmailField(label='EmailField')
    #filefield = forms.FileField(label='FileField')
    floatfield = forms.FloatField(label='FloatField', max_value=23.6, min_value=-5.32)
    integerfield = forms.IntegerField(label='IntegerField', max_value=66, min_value=22)
    ipaddressfield = forms.IPAddressField(label='IPAddressField')
    multiplechoicefield = forms.MultipleChoiceField(label='MultipleChoiceField', choices=CHOICES)
    nullbooleanfield = forms.NullBooleanField(label='NullBooleanField')
    regexfield = forms.RegexField(label='RegexField', regex=r'^[\w\.\-]+$', error_messages={
        'invalid': 'Value may only contain letters, numbers, fullstop and dash'})
    timefield = forms.TimeField(label='TimeField')
    urlfield = forms.URLField(label='URLField')

class Example2(forms.Form):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput())
    password1 = forms.CharField(label='New Password', min_length=6, widget=forms.PasswordInput(),
        help_text = "at least 6 characters (case sensitive)")
    password2 = forms.CharField(label='New Password (again)', required=True, widget=forms.PasswordInput())

    class Ajax:
        rules = [
            ('password2', {'equal_to_field': 'password1'})
        ]
        messages = [
            ('password2', {'equal_to_field': "Password fields didn't match."})
        ]


class Example3(forms.Form):
    username = forms.RegexField(max_length=30, regex=r'^[\w\.\-]+$',  widget=forms.TextInput(),
        help_text = "Alphanumeric value must with at most 30 characters",
        error_message = "This value must contain only letters, numbers and underscores.")
    email = forms.EmailField(label="E-mail", widget=forms.TextInput())
    password1 = forms.CharField(label='New Password', min_length=6, widget=forms.PasswordInput(),
        help_text = "at least 6 characters (case sensitive)")
    password2 = forms.CharField(label='New Password (again)', required=True, widget=forms.PasswordInput())

    class Ajax:
        callback_url = 'ajax_example3'
        callback_fields = ['username', 'email']
        rules = [
            ('password2', {'equal_to_field': 'password1'})
        ]
        messages = [
            ('password2', {'equal_to_field': "Password fields didn't match."})
        ]

    def clean_username(self):
        pass

    def clean_email(self):
        pass


class Example4(forms.Form):
    pass

example/foo/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

from forms import Example1, Example2, Example3, Example4


def example1(request, form_class=Example1,
        template_name="foo/example1.html"):
    message = None
    if request.method == "POST":
        form = form_class(request.POST)
        if form.is_valid():
            message = "OK"
    else:
        form = form_class()
    return render_to_response(template_name, {
        "form": form,
        "message": message,
    }, context_instance=RequestContext(request))


def example2(request, form_class=Example2,
        template_name="foo/example2.html"):
    message = None
    if request.method == "POST":
        form = form_class(request.POST, prefix="test")
        if form.is_valid():
            message = "OK"
    else:
        form = form_class(prefix="test")
    return render_to_response(template_name, {
        "form": form,
        "message": message,
    }, context_instance=RequestContext(request))


def example3(request, form_class=Example3,
        template_name="foo/example3.html"):
    message = None
    if request.method == "POST":
        form = form_class(request.POST)
        if form.is_valid():
            message = "OK"
    else:
        form = form_class()
    return render_to_response(template_name, {
        "form": form,
        "message": message,
    }, context_instance=RequestContext(request))


def example4(request, form_class=Example4,
        template_name="foo/example4.html"):
    message = None
    if request.method == "POST":
        form = form_class(request.POST)
        if form.is_valid():
            message = "OK"
    else:
        form = form_class()
    return render_to_response(template_name, {
        "form": form,
        "message": message,
    }, context_instance=RequestContext(request))

example/foo/templates/foo/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>AJAX Forms: {% block head_title %}{% endblock %}</title>
        <link rel="shortcut icon" type="image/ico" href="{{ STATIC_URL }}favicon.ico" />
        <style>
            input, select {
                border: 1px solid #666;
            }
            .valid input,
            .valid select {
                background: #EFE;
            }
            .invalid input,
            .invalid select {
                background: #FEE;
                border-color: #F66;
            }
            .processing input,
            .processing select {
                background: #EEE;
            }
            th {
                text-align: left;
                vertical-align: top;
            }
            form .required {
                padding-left: 0.5em;
                color: red;
            }
            {% block extra_style %}{% endblock %}
        </style>
    </head>
    <body>
        <h1>AJAX Forms Example</h1>

        {% block body %}{% endblock %}

        <!-- Put scripts last as per Yahoo Best Practices @see http://developer.yahoo.com/performance/rules.html#js_bottom -->
        <!--script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script-->
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.1.3.min.js"></script>
        {% block javascript %}
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ajax_forms.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ajax_forms.validation.js"></script>
        {% endblock %}
        {% block extra_body %}{% endblock %}
    </body>
</html>

example/foo/templates/foo/example1.html
{% extends "foo/base.html" %}
{% load ajax_form_utils %}

{% block head_title %}Example 1{% endblock %}

{% block extra_style %}
form dl {}
form dt {
    float: left;
    width: 12em;
}
form dd {
    margin: 0 0 1em 12.5em;
}
form .errorlist {
    margin: 0;
    padding: 0.5em 0 0 2em;
    color: red;
}
{% endblock %}

{% block body %}
    <h2>Example 1</h2>
    <p>Form with all basic field types.</p>

    <form method="post">
        {% csrf_token %}
        <dl>
            {% as_dl form %}
            <dd><input type="submit" /></dd>
        </dl>
    </form>
{% endblock %}

{% block extra_body %}
<script type="text/javascript">
    $(function() {
        $('#id_boolean').focus();
        $('form').validation({% render_ajax_fields form %}, {
            layout: 'dl',
            validation_events: ['blur', 'keyup'],
            add_required_indicators: true
        });
    });
</script>
{% endblock %}

example/foo/templates/foo/example2.html
{% extends "foo/base.html" %}

{% block head_title %}Example 2{% endblock %}

{% block body %}
    <h2>Example 2</h2>
    <p>Form with extended "Meta" options.</p>

    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr><td></td><td><input type="submit" /></td></tr>
        </table>
    </form>
{% endblock %}

{% load ajax_form_utils %}
{% block extra_body %}
<script type="text/javascript">
    $(function() {
        $('form').validation({% render_ajax_fields form %}, {
            add_required_indicators: true
        });
    });
</script>
{% endblock %}

example/foo/templates/foo/example3.html
{% extends "foo/base.html" %}

{% block head_title %}Example 3{% endblock %}

{% block body %}
    <h2>Example 3</h2>
    <p>Form with AJAX callback.</p>

    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr><td></td><td><input type="submit" /></td></tr>
        </table>
    </form>
{% endblock %}

{% load ajax_form_utils %}
{% block extra_body %}
<script type="text/javascript">
    $(function() {
        $('form').validation({% render_ajax_fields form %});
    });
</script>
{% endblock %}

example/foo/templates/foo/example4.html
{% extends "foo/base.html" %}

{% block head_title %}Example 4{% endblock %}

{% block body %}
    <h2>Example 4</h2>
    <p>Form with custom fields.</p>

    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr><td></td><td><input type="submit" /></td></tr>
        </table>
    </form>
{% endblock %}

{% load ajax_form_utils %}
{% block extra_body %}
<script type="text/javascript">
    $(function() {
        $('form').validation({% render_ajax_fields form %});
    });
</script>
{% endblock %}

example/foo/templates/foo/form_dl.html
{% for field in form %}
	<dt>{{ field.label_tag }}</dt>
	<dd>
		{{ field }}
		{% if field.help_text %}{{ field.help_text }}{% endif %}
		{{ field.errors }}
	</dd>
{% endfor %}

example/foo/templates/foo/home.html
{% extends "foo/base.html" %}

{% block head_title %}Example Forms{% endblock %}

{% block body %}
    <h2>Example Forms</h2>

    <ul>
        <li><a href="{% url example1 %}">Example 1</a> - Form with all basic field types.</li>
        <li><a href="{% url example2 %}">Example 2</a> - Form with extended "Meta" options.</li>
        <li><a href="{% url example3 %}">Example 3</a> - Form with AJAX callback.</li>
        <li><a href="{% url example4 %}">Example 4</a> - Form with custom fields.</li>
    </ul>
{% endblock %}

example/foo/templates/foo/test.html
{% extends "foo/base.html" %}

{% block head_title %}Example 4{% endblock %}

{% block body %}
    <h2>Regex Test</h2>
    
    <input id="re" type="text" size="50" />
    <input id="try" type="button" value="Try" /><br />
    <textarea id="match" type="text" cols="70" rows="5"></textarea>
    <div id="result"></div>
{% endblock %}

{% block extra_body %}
<script type="text/javascript">
    $(function() {
    	function test() {
    	    var expression = $('#re').val();
    	    var result = '';
    	    try {
    	    	var re = new RegExp(expression);
    	    	//var re = eval(expression);
    	    	var match = re.exec($('#match').val());
    	    
    	    	for (var idx in match) {
    	        	result += match[idx] + '<br />';
    	    	}
    	    } catch(e) {
    	    	result = e.message;
    	    }
    	    $('#result').html(result);
    	}
    	
    	$('#match').keyup(test);
    	$('#try').click(test);
    });
</script>
{% endblock %}